version: "3.2"

services:
  smartcontract:
    build:
      context: .
    container_name: "smartcontract"
    volumes:
      - type: bind
        source: ./
        target: /home/node/app/
      - /home/node/app/node_modules
    ports:
      - "8089:8000"
    networks:
      - net
    entrypoint: sh
    command: '-c "sleep 1d"'
    env_file:
      - ./.env
networks:
  net:
